# Conclusion et discussion {-}  

L'infertilité Est une problématique à laquelle font face entre 10 et 15% des couples humains [@Boivin2007a] faisant de cette pathologie un enjeux de santé publique. Bien que les causes de ce phénotypes puissent être multifactorielles et aquises au cours de la vie de l'individus, notamment suite à des infections du système urogénitale ou encore à des perturbations du système endocrinien, la composante génétique est extrêmement importante. À jour, malgres les efforts de nombreuses équipes, incluant lma notre, seulement une poignée de gène ont pu être relié à ce phénotype. De plus, pour nombre d'entre eux, les bases moléculaires reliant une mutation au phénotype d'infertilité restent inconnues.  

Dès lors, la première partie de mon travail de thèse à consister à contribuer à la caractérisation du phénotype de globozoospermie. Ce phénotype, entrainant la production dse 100% de spermatozoïdes à têtes rondes et dépourvus d'acrosomes est dans principalement causé, chez l'humain, par une délétion homozygote récurrente entrainant la totalité de la séquence du gène *DPY19L2*.  Ainsi, dans deux études différentes, nous avons pu, dans un premiers temps, mieux caractériser les mécanismes moléculaires responsables de cette délétion. Ainsi, nous avons pu mettre en évidence cinq points de cassures aux niveau des LCRs flanquant la séquence de *DPY19L2* chez l'humain. Ceux-ci étant tous concentrés dans une région d'environ 1150 pb contenant en son centre un site de reconaissance consensus de la protéine PRDM9 connue pour son implication dans la recombinaison chromosimique chez l'humain et la souris [@Parvanov2010; @Baudat2010]. Cette même étude a également permis de démontrer que les effets de la séléction naturelle étaient responsables du paradoxe consistant à observer plus fréquemment, dans la population générale, l'allèle dupliqué à ce locus que l'allèle délété tandis que *de novo* l'allèle délété est produit, en théorie et en pratique, plus fréquement que l'allèle dupliqué. L'étude de ce phénotype nous a part la suite poussé à étudié le modèle murin KO *Dpy19l2*^-/-^ présentant le même phénotype que l'humain. Afin d'expliquer l'absence de la protéine PLC$\zeta$ chez l'humain globozoosperme, nous avecs effectués une analyse comparatives des transcriptomes testiculaires de souris sauvages *Dpy19l2*^+/+^ et KO *Dpy19l2*^-/-^. Bien qu'aucun déréglement transcriptionel n'est pu être observé pour le gène *Plc*$\zeta$ cette étude nous a permis de mettre en évidence un total de 75 gènes présentant des dérégulations transcriptionelles pouvant expliquer en partie les anomalies physiologiques et morphologiques des spermatozoïdes des souris*Dpy19l2*^-/-^.    

Esuite, notre équipe ayant, entre ... et ...,  a effectué le séquençage exomique de plusieurs patients présentant tous un phénotype d'infertilité, la seconde partie de mon travail de thèse a été de mettre au point un pipeline permettant l'analyse des données générées lors du processus de séquençage. Celui-ci ayant pour vocation première de mettre en évidence les variants responsables des phénotypes de ces patients. Contrairement à la plupart des pipelines d'analyse de données WES existant, clui-ci prend en charge l'ensemble des étapes de l'analyse allant de l'alignement des *short-reads* sur le génome de référence jusqu'à la priorisation des variants en passant bien évidemment par l'appel des variants et leur annotation. Les résultats de chacune de ces étapes pouvant être controlés et personalisés grâce à des paramètres ajustables. L'alignements des *reads* est effectué par le logiciel MAGIC tandis que les variants et leur gnotypes sont appelés par un algorithme développé dans notre laboratoir spécifiquement conçu pour analyser les informations fournies par MAGIC et dont les paramètres sont ajustables en fonctions de la distribution des pourcentages de *reads* variants observés dans les données analysées. Pour l'annotation nous avons utilisé plusieurs ressources exterieures tel que le logiciel Variant Effect Predictor qui va nous informer de l'effet d'un variant sur l'ensemble des transcrits qu'il chevauche. De même, les bases de données ExAC ESP6500 ou encore 1KG nous donne une indication de la fréquence des variants dans la population générale. Une fois ces étapes effectuées, nous avons mis en place plusieurs filtres succesifs afin d'éliminer de nos listes les variants ayant le moins de chances d'être responsables du phénotypes des différentes patients. Ceux-ci s'appuient à la fois sur les critères qualité des résultats de séquençage, le génotype des variants, leur fréquence ou encore leur impact sur la protéine.  

L'efficacité de ce pipeline a pu être démontré grâce à son utilisation utilisation sur des cas familiaux mais aussi sur des cohortes d'individus non apparentés. Ainsi, nous avons pu dans un premier temps confirmer l'importance de l'implication du gène *DNAH1* dans le syndrome MMAF en le retrouvant muté chez ... de nos patients. Ensuite, dans un second temps, ce pipeline nous a permis de mettre en évidence un total de 5 nouveaux dans des phénotypes d'infertilité masculine et féminine. Ainsi les gènes *CFPA43*, *CFAP44*, retrouvés respectivement mutés chez ... et ... de nos patients ont pu être liés à leur syndrome MMAF. Aussi, une même mutation impactant le gène PATL2 a pu être relié au phénotype de déficience méiotique ovocytaire de cinq femmes. Pour finir, des mutations sur les gènes *SPINK2* et *PLC*$\zeta$, ont elles aussi pu être liées aux phénotypes d'azoospermie et d'echec de fécondation dont étaient atteins deux fratries.  

Ces résultats sont cependant à relativiser puisque pour plusieurs de nos patients, aucun candidat n'a pu être identifié. Plusieurs raison peuvent expliquer cela. Tout d'abord, au cours des analyses décrites dans ces manuscrits nous nous concentrons uniquements sur les SNPs et les indels. Cependant de nombreux logiciels tel que ..., ... ou encore ... permettent de détecter des CNVs à partir de données WES et / ou WGS. Les stratégies de prédictions de ces logiciels pouvant être êxtremement différents, le profil des CNVs détécté ou non le sera aussi [ref ]. Ainsi, dans des analyses non décrites ici, j'ai pu chercher à identifier des CNVs à partir de nos données d'exome à l'aide du logiciel ExomeDepth [REF]. Cette approche a été extrêmement concluante puisqu'elle a permi d'identifier une délétion homozygote sur le gène *WDR66* de ... de nos patiens pour lesquels aucun candidat n'avait été alors identifié. Ces délétions ont ensuite pu être confirmées par PCR et la caractérisation de ce gène est actuellement en cours au sein de notre équipe. Au vu de cette réussite, il est désormai prévu d'intégrer ce genre d'analyse de manière automatique et systématique au sein de notre pipeline. Pour les autres patients n'ayant eu aucun candidat identifié, il est possible que le choix de la stratégie d'un séquençage exomique plutôt que du génome entier ait masqué la cause génétique du phénotype de certains de nos patients. En effet, dans ces analyses, nous nous sommes concentrés sur l'analyse des variants situés dans les parties codantes **uniquement**. Ainsi les variants situés par exemple dans les microARN n'ont pu être observés. Or, les microARN jouent un rôle important dans la régulation génique principalement en influant sur la stabilité d'ARNm cibles et sont présent en grande quantité au sein des cellules germinales et leur importance dans la spermatogénèse a déjà été démontrée chez la souris [@Comazzetto2014] ainsi que plus récemment chez d'autres mammifères dont l'Humain [@Chen2017] laissant penser que des defauts altérants ces microARN pourraient entrainer des dysfonctionnement de la spermatogenèse. Aussi, il faut noter que les analyses WES **et** WGS ne permettent pas d'observer les défauts épigénétiques, or, ceux-ci représentent une part croissante des causes impliquées dans les cas d'infertilité masculine [@Carrell2011, @Dada2011, @Dada2012]. Aussi, au vus du grand nombre de gène impliqué dans la spermatogénèse il est très possible que les causes génétique responsables d'un même phénotype puissent être très hétérogène. Par exemple, dans le cas de l'analyse de la cohorte de patients MMAF, ... variants subsistaient après avoir appliquer l'ensemble des filtres. Ces variants impactaient ... gènes différents parmi lesquels ... étaient retrouvé muté chez uniquement un seul des ... patients de la cohorte. Au vu de se nombre important de gène, il est très compliqué d'effectué des analyses poussées sur l'ensemble d'entre eux. Dès lors, il est possible que la cause génétique responsable du phénotype d'un patient soit "noyé" parmi les nombreux variants restant mettant ainsi en évidence la nécéssité de créer de nouveaux filtres afin de pouvoir réduire encore cette liste.  

C'est dans ce but que notre équipe travail actuellement au développement du score MutaScript. Ce score a pour but de classer l'ensemble des transcrit codant en fonction de leur charge mutationnelle avec l'idée sous-jacente que les transcrits les plus mutés dans la population générale ne sont probablement pas impliqués dans des pathologies sévères à transmission Mendélienne, *a contrario* ceux retrouvés comme n'étant pas / peu mutés le sont probablement. Pour ce faire, le score MutaScript repose sur trois (...). La première étant le jeu de transcrit fournit par Ensembl [@Aken2017]. Afin de connaitre la charge mutationnelle de ces transcrits, nous nous sommes basées sur les variants mis à disposition par ExAC [@Lek2016] qui réunit les données d'exome de 60.706 individus non apparentés que nous avons ensuite annoté grâce au logiciel *variant effect predictor* (VEP) [@McLaren2016] afin de prédire l'impact de chaque variant sur l'ensemble des transcrits qu'ils chevauchent de sorte à ce que les variants ayant un impact prédit comme étant délétère aient une plus grosse contribution au score MutaScript que ceux ayant un impact faible. Ces dernières années, des scores tel que le *residual variance intolerance score* (RVIS) [@Petrovski2013] ou encore *the the Probability of loss-of-function Incoherency* (pLI) [@Lek2016] ont vu le jour. MutaScript se présente comme une alternative à ces derniers scores et, bien que sa fonction soit similaire, il diffère de ceux-ci sur de nombreux points. Tout d'abord, MutaScript donne un score à l'ensemble des transcrits codant pour une protéine là où pLI donne un score seulement au transcrit consensus de chaque gène et RVIS qui agrège les séquences codantes de l'ensemble des transcrits d'un même gène créant ainsi un transcrit "chimérique". Ce procédé, bien qu'il facilite l'interprétation du score, engendre une perte d'information puisque l'on se retrouve avec un seul score par gène et non par transcrits. De plus, dans la conception de leur score, RVIS et pLI ne considère que les variants dit *loss-of-function* (LoF), c'est à dire les variants impactant l'épissage, engendrant un codon stop ou un décalage du cadre de lecture. Cependant, ces variants ne représentent que ...% des variants fournit par la base de données ExAC. C'est pourquoi, MutaScript prend en compte l'ensemble des variants, peu importe leur impact sur les différents transcrits qu'ils chevauchent, et leur attribue un poids en fonction de cet impact de sorte à ce que les variants délétères contribuent plus au score d'un transcrits que les autres. Aussi, l'étude des scores RVIS et pLI nous a permis de mettre en évidence une corrélation forte entre le score qu'ils attribuent à un gène et la taille de la séquence codante (CDS) de ce même gène. Cette corrélation étant due à un biais causé par leur manière de calculer leur score et non à une réalité biologique, MutaScript fut construit de sorte à éviter cette corrélation qui peut mener à des erreurs d'interprétations. Le développement de ce score étant en cours de finalisation.

***

Pendant de nombreuses années, la Science et la Technique étaient considérées comme des disiplines distinctes. Elles étaient pratiquées, dans la grande majorité des cas, de manière indépendantes l'une de l'autre et surtout par des personnes différentes n'entretennant aucune intéraction. Bien que la distinction entre Science et Technique soit réelle, la première pouvant être définie comme la quête de la connaissance et de la compréhension du monde tandis que la seconde met en oeuvre un ensemble de moyen afin de modifier celui-ci d'une manière déterminée à l'avance, l'inter-dépendance liant ces deux notions n'a jamais été aussi forte qu'à notre époque tant et si bien qu'elles sont souvent confondues. En effet, il est courant d'entendre parler de progrès scientifique pour présenter une innovation technologique et *vice versa*. Ainsi, si la Science n'est pas la Technique, elle est dans de nombreux cas dépendante de celle-ci. En effet, comme nous avons pu le voir, l'étude et la connaissance du génome ont du attendre les progrès techniques permettant notamment le séquençage de l'ADN. La Technique, elle, n'a pas nécessairement besoin de savoirs scientifiques pour être conçue : des savoirs empiriquement acquis suffisent à l'application d'une technique. Par exemple, bien qu'ils n'aient eu aucune conscience des mécanismes scientifiques sous-jacent, les premiers Hommes ont su maitriser plusieurs techniques de production et d'entretien du feu. De la même manière les agriculteurs n'ont pas eu besoin d'attendre et de comprendre les travaux sur la génétique et l'hérédité pour observer que la mise en reproduction des bêtes les plus productives permettait de maximiser les chances que la déscendance soit elle aussi très productive. Cependant la Technique utilise de plus en plus des connaissances scientifiques et a ainsi finit par beaucoup dépendre d'Elle en utilisant et appliquant des savoirs scientifiques. Ainsi est né la Technologie. Les travaux décrits dans ce manuscrits illustrent parfaitement cette relation d'interdépendance entre la Science et le Technique / Technologie. En effet, la connaissance du génome a été permise par l'émmergence des différentes technologies de séquençage qui s'appuies elles aussi sur de nombreuses connaissances scientifiques. On peut dès lors s'attendre à ce que Science et Techniques / Technologie continuent d'évoluer de manière concomitantes en s'entre allimentant. Dès lors, on peut prédire que les prochains progrès technologiques seront à l'origine de découvertes scientifiques qui serviront elles même à la fois de socle mais aussi de guide aux évolutions technologiques futures. 
 