`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

#  : Article DNAH1

Article DNAH1 2014


\newpage

# Table des variants retrouvés sur le gène *DNAH1*  

```{r tabdnah1, dependson="dfbigmmaffilter", cache=TRUE}

caption <- "Table des variants retrouvés sur le gène *DNAH1*"

df_dnah1 <- bind_rows(df_bigmmaf_filter, df_bigmmaf_filter_het) %>%
  filter(SYMBOL == "DNAH1") %>%
  filter(CANONICAL == "YES") %>%
  mutate(CALL = substr(CALL, start=1, stop=4),
         HGVSc = na.replace(HGVSc, "."),
         HGVSp = na.replace(HGVSp, "."),
         ExAC_AF = na.replace(ExAC_AF, "."),
         ESP = na.replace(ESP, "."),
         `1KG` = na.replace(`1KG`, "."),
         `ExAC ; ESP ; 1KG` = paste(ExAC_AF, ESP, `1KG`, sep = " ; "),
         `HGVSc, HGVSp` = paste(HGVSc, HGVSp, sep = " ; ")) %>%
  select(Patient = RUN, Gene = SYMBOL, Geno = CALL, `HGVSc, HGVSp`, Consequence, `ExAC ; ESP ; 1KG`)

   kable(df_dnah1  %>%  select(-Gene) %>% arrange(desc(Geno), Patient, `HGVSc, HGVSp`),
     format = "latex",
          booktabs = TRUE,
          longtable = TRUE,
          caption = caption) %>%
  landscape() %>%
  add_header_above(c(" " = 2, "Variant impact" = 2, "Variant frequency"))

```

\newpage

# Table des variants retrouvés sur le gène *CFAP43*  

```{r tabcfap43, dependson="dfbigmmaffilter", cache=TRUE}

caption <- "Table des variants retrouvés sur le gène *CFAP43*"

df_dnah1 <- bind_rows(df_bigmmaf_filter, df_bigmmaf_filter_het) %>%
  filter(SYMBOL == "CFAP43") %>%
  filter(CANONICAL == "YES") %>%
  mutate(CALL = substr(CALL, start=1, stop=4),
         HGVSc = na.replace(HGVSc, "."),
         HGVSp = na.replace(HGVSp, "."),
         ExAC_AF = na.replace(ExAC_AF, "."),
         ESP = na.replace(ESP, "."),
         `1KG` = na.replace(`1KG`, "."),
         `ExAC ; ESP ; 1KG` = paste(ExAC_AF, ESP, `1KG`, sep = " ; "),
         `HGVSc, HGVSp` = paste(HGVSc, HGVSp, sep = " ; ")) %>%
  select(Patient = RUN, Gene = SYMBOL, Geno = CALL, `HGVSc, HGVSp`, Consequence, `ExAC ; ESP ; 1KG`)

   kable(df_dnah1  %>%  select(-Gene) %>% arrange(desc(Geno), Patient, `HGVSc, HGVSp`),
     format = "latex",
          booktabs = TRUE,
          longtable = TRUE,
          caption = caption) %>%
  landscape() %>%
  add_header_above(c(" " = 2, "Variant impact" = 2, "Variant frequency"))

```

\newpage

# Table des variants retrouvés sur le gène *CFAP44*  


```{r tabcfap44, dependson="dfbigmmaffilter", cache=TRUE}

caption <- "Table des variants retrouvés sur le gène *CFAP44*"

df_dnah1 <- bind_rows(df_bigmmaf_filter, df_bigmmaf_filter_het) %>%
  filter(SYMBOL == "CFAP44") %>%
  filter(CANONICAL == "YES") %>%
  mutate(CALL = substr(CALL, start=1, stop=4),
         HGVSc = na.replace(HGVSc, "."),
         HGVSp = na.replace(HGVSp, "."),
         ExAC_AF = na.replace(ExAC_AF, "."),
         ESP = na.replace(ESP, "."),
         `1KG` = na.replace(`1KG`, "."),
         `ExAC ; ESP ; 1KG` = paste(ExAC_AF, ESP, `1KG`, sep = " ; "),
         `HGVSc, HGVSp` = paste(HGVSc, HGVSp, sep = " ; ")) %>%
  select(Patient = RUN, Gene = SYMBOL, Geno = CALL, `HGVSc, HGVSp`, Consequence, `ExAC ; ESP ; 1KG`)

   kable(df_dnah1  %>%  select(-Gene) %>% arrange(desc(Geno), Patient, `HGVSc, HGVSp`),
     format = "latex",
          booktabs = TRUE,
          longtable = TRUE,
          caption = caption) %>%
  landscape() %>%
  add_header_above(c(" " = 2, "Variant impact" = 2, "Variant frequency"))

```

\newpage

```{r, message=FALSE, warning=FALSE}
# 
# tab_annexe <- function(df_homo, df_het, cap = "") {
#   
#   df_high <- df_homo %>% 
#     filter(CANONICAL == "YES", 
#            IMPACT == "HIGH") %>%
#     group_by(SYMBOL, EVIDENCE, Feature) %>% 
#     summarise(N_HIGH = n_distinct(RUN))
#   
#   df_not_high <- df_homo %>% 
#     filter(CANONICAL == "YES", 
#            IMPACT != "HIGH") %>%
#     group_by(SYMBOL, EVIDENCE, Feature) %>% 
#     summarise(N_NOT_HIGH = n_distinct(RUN))
#   
#   df_het <- df_het %>% filter(CANONICAL == "YES") %>% 
#     group_by(SYMBOL, EVIDENCE, Feature) %>% 
#     summarise(N_COMP_HET = n_distinct(RUN))
#   
#   
#   df_all <- df_high %>%
#     left_join(df_not_high) %>%
#     left_join(df_het)
#   
#   df_all %>% 
#     mutate(N_NOT_HIGH = na.replace(N_NOT_HIGH, 0),
#            N_COMP_HET = na.replace(N_COMP_HET, 0),
#            N_TOT = N_HIGH + N_NOT_HIGH + N_COMP_HET) %>%
#     arrange(desc(EVIDENCE), desc(N_HIGH), desc(N_TOT), SYMBOL) %>%
#     select(Gene = SYMBOL, `Ciliome evidence` = EVIDENCE, `Tronquant` = N_HIGH, `Non tronquant` = N_NOT_HIGH,`>= 2 variants` = N_COMP_HET) %>%
#   kable(format = "latex",
#         booktabs = TRUE,
#         longtable = TRUE,
#         caption = cap) %>%
#     add_header_above(c(rep(" ", 2), "Homozygous" = 2, "Heterozygous" = 1)) %>%
#     
#     add_header_above(c(rep(" ", 2), "Nb of patient with : " = 3))
# }
# 

```
